### ISSUE TITLE
[Feature Request] Independent layers

### ISSUE THREAD

**Issue by SimonBiggs** [seddonym/layer_linter#88]
* Layer Linter version: 0.12.0
* Python version: 3.6
* Operating System: Ubuntu 18.04

### Description

Hi! :) We've just begun implementing this library within our project:

https://gitlab.com/pymedphys/pymedphys/blob/varian-logfiles/layers.yml

It's amazing! :) Thank you very much. Also, it plays quite nice with pytest:

https://gitlab.com/pymedphys/pymedphys/blob/varian-logfiles/tests/test_project_architecture/test_layering.py

I do have one request. In your rocky river architecture (http://seddonym.me/2018/09/16/rocky-river-pattern/) you produced a diagram. In that particular diagram the river itself was also layers/levelled. You essentially had 5 layers in that rocky river. I have circled the layers below:

![rockyriver](https://user-images.githubusercontent.com/6559099/51444889-0af71700-1d52-11e9-8c40-0db29ffff8f0.png)

What I was hoping was to be able to do is enforce a structure where those modules are on the same level as each other, unable to depend on each other, but all able to depend on those lower than them.

A way I thought that this might look in the yaml file is:

```yaml
Top Level Modules:
    containers:
        - pymedphys
    layers:
        - logfile
        - trf
        - msq
        -
            - mudensity
            - pddprofiles
            - gamma
            - coll
        - 
            - electronfactors
            - film
            - sinogram
            - dcm
            - utilities
        -
            - deliverydata
            - geometry
            - plt
            - filehash
            - xarray
        - libutils
```

Essentially any module within a nested list are all considered on the same level as each other. Any of those cannot import from each other, but can import from those lower than them.

What do you think?
