### ISSUE TITLE
External dependencies

### ISSUE THREAD

**Issue by sobolevn** [seddonym/layer_linter#91]
I am using a sort-of-hexagonal-architecture.

So, my use-case is: I want to forbid imports of `django` (in my case, can be `flask`, etc) inside my domain level.

Currently it seems like an impossible task.
But, it seems rather practical for people who care about their architecture.

Proposed syntax:

```yml
Global architecture:
  containers:
    - common
  layers:
    - domain
    - @django
```

Or even new field can be applied:

```yml
Global architecture:
  containers:
    - common
  layers:
    - domain
    ...
  constraints:
    - @django
```
