### ISSUE TITLE
alternate contracts - layer whitelists

### ISSUE THREAD

**Issue by toejough** [seddonym/layer_linter#96]
I love the idea of this tool, and I've started to add it to my projects at home and at work!

I was adding some color/additional-requests to #91 , and I realized what I was asking for was actually different enough that I should open a different issue.

Given a package structure like:
```
package/
  adapters/
    front_end.py
    back_end.py
  core/
    data.py
    logic.py
```

...in plain-ish english, what I'd like to have a contract for is a hexagonal-ish architecture:
* anything in the project can import from the standard lib
* anything in the project can import from `core.data`
* any `adapter` can import from third party sources
* `adapters.front_end` may import from `core.logic`
* nothing else is allowed (`adapters.front_end` may not import `adapters.back_end`)

I've mocked out a few of possible representations of this... I like the last one the best:

```
Nested Patterned:
    package:
        *:
            - standard library
            - core.data
        adapters:
            *:
                - third party
            front_end:
                - ..core.logic

Flat:
    package.adapters.front_end:
        - standard library
        - third party
        - package.core.logic
        - package.core.data
    package.core.logic:
        - standard library
        - package.core.data
    package.core.data:
        - standard library
    package.adapters.back_end:
        - standard library
        - third party
        - package.core.data


Flat Patterned:
    package.*:
        - standard library
        - package.core.data
    package.adapters.*:
        - third party
    package.adapters.front_end:
        - package.core.logic
```

This... is possibly an unreasonably large departure from the current contract format, so I understand if you'd rather not go down this route.  If not, though - do you have a preferred/recommended/planned way to implement the same contract?

Regardless, thanks for your work on this project - it's a big step up as-is!
